# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1aff9543b0e5b8ea93f256fce7db243f4a950638020d4b01eb8fadc07b426b9dcda68ab28bd08703354b8dea576ee79344075c8cc44e7fe752c7735daf4a996

test:
  secret_key_base: 91d7df027ff4ed0d02a7e06909a333c4a90f0df39557ba30a6e91316ad9e2c58bab0253a23e4169c06c930fce6744f98f2163ba1584ff843faf2af8e2034ef03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
